USE [master]
GO

/****** Object:  Database [юПР╦Лопндюфх]    Script Date: 11.02.2022 14:27:59 ******/
CREATE DATABASE [юПР╦Лопндюфх]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'юПР╦Лопндюфх', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\юПР╦Лопндюфх.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'юПР╦Лопндюфх_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\юПР╦Лопндюфх_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [юПР╦Лопндюфх].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ARITHABORT OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET  DISABLE_BROKER 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET RECOVERY FULL 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET  MULTI_USER 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [юПР╦Лопндюфх] SET DB_CHAINING OFF 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [юПР╦Лопндюфх] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [юПР╦Лопндюфх] SET QUERY_STORE = OFF
GO

ALTER DATABASE [юПР╦Лопндюфх] SET  READ_WRITE 
GO


